version: 2

sources:
  - name: tpch
    description: "Fuentes raw del dataset TPCH cargadas en Snowflake para el proyecto analítico."
    database: PRACTICA_DWH
    schema: RAW_TPCH

    tables:
      - name: customer
        description: "Tabla raw de clientes."
      - name: orders
        description: "Tabla raw de pedidos."
      - name: lineitem
        description: "Tabla raw de líneas de pedido."
      - name: part
        description: "Tabla raw de productos."
      - name: partsupp
        description: "Tabla raw de relación entre productos y proveedores."
      - name: supplier
        description: "Tabla raw de proveedores."
      - name: nation
        description: "Tabla raw de naciones."
      - name: region
        description: "Tabla raw de regiones."